name: autodeploy-infomaniak

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '8.10.0'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
        
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: SFTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./web/